<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>    
    <!-- NuGet Metadata -->
    <AssemblyName>LayerZero.Tools.Web</AssemblyName>
    <PackageId>LayerZero.Tools.Web</PackageId>
    <Version>2.0.0</Version>
    <Authors>RuneForgePrime</Authors>
    <Company>LayerZero</Company>
    <Description>Convention-based dynamic JS/CSS bundling and injection system for ASP.NET Core using WebOptimizer.</Description>
    <RepositoryUrl>https://github.com/RuneForgePrime/LayerZero</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/RuneForgePrime/LayerZero</PackageProjectUrl>
    <PackageTags>weboptimizer;bundle;aspnetcore;razor;taghelpers</PackageTags>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>Icon/weblogo.png</PackageIcon>
  </PropertyGroup>


  <ItemGroup>
    <None Include="Icon\weblogo.png" Pack="true" PackagePath="Icon\" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AngleSharp.Css" Version="0.17.0" />
    <PackageReference Include="Esprima" Version="3.0.5" />
    <PackageReference Include="LayerZero.Tools" Version="1.0.2" />
    <PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.436" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="CHANGELOG.md" Pack="true" PackagePath="">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
